adds deal Client frontend
FIL-Builders/fil-frame pull request #46
Opened 2024-11-02 12:36 UTC by nijoe1

## Description

_Concise description of proposed changes, We recommend using screenshots and videos for better description_

## Additional Information

- [ ] I have read the [contributing docs](/fil-frame/fil-frame-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/fil-frame/fil-frame-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address: lionis.eth

2024-11-03 19:05 UTC, lordshashank commented
@nijoe1 I am closing this one for now as it would be easier for you to implement this now (without use of lighthouse in UI components, directly from api) through #48 . You can commit on #48 or create a new pr after merging that one, whatever suits you. Sorry for doing this late, was quite busy in other things.

2024-11-08 05:50 UTC, xBalbinus requested changes
LGTM, please resolve merge conflicts.

2024-11-27 21:21 UTC, xBalbinus commented
Wanted to check if this is still an active pull req.

2024-12-01 21:22 UTC, lordshashank commented
I gues @nijoe1 directly pushed the code so we can close this?

2025-02-04 16:35 UTC, closed without merging